highlighter: pygments
markdown: kramdown

title : WDR - WebSphere automation library
description: WebSphere automation library
keywords: WebSphere,wsadmin,Jython,automation,DevOps
tagline: Jython framework aiming at simplifying WebSphere Application Server scripting

disclaimer: All trademarks belong to their respective owners

baseurl: /WDR
url: http://wdr.github.io

google_analytics: 'UA-44124024-1'

github : WDR/WDR
