highlighter: pygments
markdown: kramdown

title : WDR
tagline: Jython framework aiming at simplifying WebSphere Application Server scripting

disclaimer: All rademarks belong to their respective owners

baseurl: ''
url: http://localhost:4000

# google_analytics: 'UA-44124024-1'

github : WDR/WDR
